### ISSUE TITLE
ValueError("Number of processes must be at least 1")

### ISSUE THREAD

**Issue by frandlee** [yuvraj108c/4k-video-upscaler-colab#2]
I tried to run it on Colab and encountered an error as below. 
Appreciate your help. 
`sh
Upscaling from 720x1280 to 1080x1920, crop_to_fit=True
/usr/local/lib/python3.10/dist-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Traceback (most recent call last):
  File "/content/Real-ESRGAN/Real-ESRGAN/Real-ESRGAN/Real-ESRGAN/Real-ESRGAN/Real-ESRGAN/Real-ESRGAN/Real-ESRGAN/Real-ESRGAN/inference_realesrgan_video.py", line 398, in <module>
    main()
  File "/content/Real-ESRGAN/Real-ESRGAN/Real-ESRGAN/Real-ESRGAN/Real-ESRGAN/Real-ESRGAN/Real-ESRGAN/Real-ESRGAN/Real-ESRGAN/inference_realesrgan_video.py", line 390, in main
    run(args)
  File "/content/Real-ESRGAN/Real-ESRGAN/Real-ESRGAN/Real-ESRGAN/Real-ESRGAN/Real-ESRGAN/Real-ESRGAN/Real-ESRGAN/Real-ESRGAN/inference_realesrgan_video.py", line 296, in run
    pool = ctx.Pool(num_process)
  File "/usr/lib/python3.10/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
Cropping to fit done..
Upscaled video saved to: /content/IMG_0963.MOV_upscaled_1080_1920.mp4
Saved to drive: /MyDrive/Upscaled Videos (REAL-ESRGAN)/IMG_0963.MOV_upscaled_1080_1920.mp4
`

**Comment by yuvraj108c** [comment]
Hi, you're using a cpu runtime. Please change runtime to gpu!!

**Comment by frandlee** [comment]
It works now. Thanks.
