### ISSUE TITLE
[Error]ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

### ISSUE THREAD

**Issue by negatifstoner** [yuvraj108c/4k-video-upscaler-colab#8]
It says saved right after this error shows up, and no file is saved to the folder, Help?

```
Upscaling from 1280x720 to 2560x1440, crop_to_fit=True
Traceback (most recent call last):
  File "/content/Real-ESRGAN/Real-ESRGAN/Real-ESRGAN/inference_realesrgan_video.py", line 10, in <module>
    from basicsr.archs.rrdbnet_arch import RRDBNet
  File "/usr/local/lib/python3.10/dist-packages/basicsr/__init__.py", line 4, in <module>
    from .data import *
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/realesrgan_dataset.py", line 11, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'
Cropping to fit done..
Upscaled video saved to: /content/easy fraktal street_upscaled_2560_1440.mp4
```

**Comment by Benjamim-EP** [comment]
use 

`pip install torch==2.0.1 torchvision==0.15.2 --extra-index-url https://download.pytorch.org/whl/cu118`

**Comment by negatifstoner** [comment]
Thanks! Seems like its working now, will let u know what happens when it is done loading.
```
Upscaling from 1280x720 to 3840x2160, crop_to_fit=True
/usr/local/lib/python3.10/dist-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Downloading: "https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.2.4/RealESRGAN_x4plus_anime_6B.pth" to /content/Real-ESRGAN/weights/RealESRGAN_x4plus_anime_6B.pth

100% 17.1M/17.1M [00:00<00:00, 346MB/s]
inference:   3% 70/2715 [02:46<1:45:21,  2.39s/frame]
```

**Comment by yuvraj108c** [comment]
Fixed the issue. Thanks @Benjamim-EP for providing the solution!
